VCF_DIR=<full path of directory containing the VCFs>
FASTA_DIR=<full path of directory with reference genome indicated in VCF file>
GEMINI_DB_SUFFIX=db
CPU_NB=8
TOOL_PATH=<full path of directory containing the software listed below>
TABIX=tabix-0.2.6
VT=vt
VEP=ensembl-tools-release-82/scripts/variant_effect_predictor
GEMINI=gemini/bin
VCFTOOL=vcftools-0.1.14/bin
VCFTOOL_PERL=vcftools-0.1.14/src/perl
LSF_PATH=<full path of LSF software e.g. /mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64>
MEMORY_REQUESTED_KB=24000000
MEMORY_REQUESTED_MB=24000
QUEUE=<queue name>
